# Use official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies directly to avoid missing file errors
RUN pip install fastapi uvicorn pandas scikit-learn multipart

# Copy the API code and the Model
COPY api/ ./api/
COPY models/ ./models/

# Expose the API port
EXPOSE 8000

# Run the API
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]